### ISSUE TITLE
nginx may silently fail to (re)start

### ISSUE THREAD

**Issue by danrue** [SPSCommerce/ansible-role-nginx#1]
If syntactically bad configuration is passed to nginx, it will silently fail to start.
To reproduce, drop a bad configuration file into nginx and observe:

    NOTIFIED: [nginx | restart nginx] ********************************************* 
    changed: [trusty]

nginx will not be running on the host. On subsequent runs, it will not be started.

**Comment by eggilbert** [comment]
I seem to be running into this too, but with good configurations. It only seems to happen to me in local ubuntu docker containers, and not out in AWS. When I spin things up from scratch, it says it fired the handler to restart things, but nginx isn't actually working. But then ssh-ing to the box and doing `service nginx restart` everything works.

**Comment by eggilbert** [comment]
Closed by: https://github.com/SPSCommerce/ansible-role-nginx/pull/8
